name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            davidbour/ccs:latest,
            davidbour/ccs:${{ github.sha }},
            davidbour/ccs:${{ github.ref_name }}-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
      - uses: Azure/setup-helm@v4.2.0

      - name: Get Helm Version
        id: helm-version
        uses: mikefarah/yq@v4.44.3
        with:
          cmd: yq '.version' ./chart/code-challenge-service/Chart.yaml

      - name: Package and Publish Helm Chart
        run: |
          helm package ./code-challenge-service --version=${{ steps.helm-version.outputs.result}}-${{ github.sha }} && \
          helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} && \
          helm push code-challenge-service-${{ steps.helm-version.outputs.result}}-${{ github.sha}}.tgz oci://registry-1.docker.io/davidbour
        working-directory: chart

      - uses: actions/checkout@v4
        with:
          repository: david-bour/code-challenge-service-config
          ref: refs/heads/main
          token: ${{ secrets.GH_API_KEY }}

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.44.3
        with:
          cmd: yq -i '.version = "${{ github.sha }}"' ./environments/dev/minikube/versions.yaml
 
      - name: Update version configuration
        run: |
          git config user.name ${{ github.actor }}
          git config user.email "<>"
          git add .
          git commit -m "Update version to ${{ github.sha }}"
          git push origin main
